apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-release-postgresql
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.2.0
automountServiceAccountToken: false